//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CogNetworks
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbCogEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbCogEntities object using the connection string found in the 'dbCogEntities' section of the application configuration file.
        /// </summary>
        public dbCogEntities() : base("name=dbCogEntities", "dbCogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbCogEntities object.
        /// </summary>
        public dbCogEntities(string connectionString) : base(connectionString, "dbCogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbCogEntities object.
        /// </summary>
        public dbCogEntities(EntityConnection connection) : base(connection, "dbCogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblLink> tblLinks
        {
            get
            {
                if ((_tblLinks == null))
                {
                    _tblLinks = base.CreateObjectSet<tblLink>("tblLinks");
                }
                return _tblLinks;
            }
        }
        private ObjectSet<tblLink> _tblLinks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblNode> tblNodes
        {
            get
            {
                if ((_tblNodes == null))
                {
                    _tblNodes = base.CreateObjectSet<tblNode>("tblNodes");
                }
                return _tblNodes;
            }
        }
        private ObjectSet<tblNode> _tblNodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblLinks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblLinks(tblLink tblLink)
        {
            base.AddObject("tblLinks", tblLink);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblNodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblNodes(tblNode tblNode)
        {
            base.AddObject("tblNodes", tblNode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCognitiveModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCognitiveModel", Name="tblLink")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblLink : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblLink object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tblLink CreatetblLink(global::System.Int32 id)
        {
            tblLink tblLink = new tblLink();
            tblLink.id = id;
            return tblLink;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> network
        {
            get
            {
                return _network;
            }
            set
            {
                OnnetworkChanging(value);
                ReportPropertyChanging("network");
                _network = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("network");
                OnnetworkChanged();
            }
        }
        private Nullable<global::System.Int32> _network;
        partial void OnnetworkChanging(Nullable<global::System.Int32> value);
        partial void OnnetworkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> startNode
        {
            get
            {
                return _startNode;
            }
            set
            {
                OnstartNodeChanging(value);
                ReportPropertyChanging("startNode");
                _startNode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startNode");
                OnstartNodeChanged();
            }
        }
        private Nullable<global::System.Int32> _startNode;
        partial void OnstartNodeChanging(Nullable<global::System.Int32> value);
        partial void OnstartNodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> endNode
        {
            get
            {
                return _endNode;
            }
            set
            {
                OnendNodeChanging(value);
                ReportPropertyChanging("endNode");
                _endNode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("endNode");
                OnendNodeChanged();
            }
        }
        private Nullable<global::System.Int32> _endNode;
        partial void OnendNodeChanging(Nullable<global::System.Int32> value);
        partial void OnendNodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> linkWeight
        {
            get
            {
                return _linkWeight;
            }
            set
            {
                OnlinkWeightChanging(value);
                ReportPropertyChanging("linkWeight");
                _linkWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("linkWeight");
                OnlinkWeightChanged();
            }
        }
        private Nullable<global::System.Int32> _linkWeight;
        partial void OnlinkWeightChanging(Nullable<global::System.Int32> value);
        partial void OnlinkWeightChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCognitiveModel", Name="tblNode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblNode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblNode object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tblNode CreatetblNode(global::System.Int32 id)
        {
            tblNode tblNode = new tblNode();
            tblNode.id = id;
            return tblNode;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> network
        {
            get
            {
                return _network;
            }
            set
            {
                OnnetworkChanging(value);
                ReportPropertyChanging("network");
                _network = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("network");
                OnnetworkChanged();
            }
        }
        private Nullable<global::System.Int32> _network;
        partial void OnnetworkChanging(Nullable<global::System.Int32> value);
        partial void OnnetworkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> node
        {
            get
            {
                return _node;
            }
            set
            {
                OnnodeChanging(value);
                ReportPropertyChanging("node");
                _node = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("node");
                OnnodeChanged();
            }
        }
        private Nullable<global::System.Int32> _node;
        partial void OnnodeChanging(Nullable<global::System.Int32> value);
        partial void OnnodeChanged();

        #endregion

    
    }

    #endregion

    
}
